/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

/**
 *
 * @author Gisele Vieira
 */
public class alterarinformações extends javax.swing.JFrame {

    /**
     * Creates new form alterarinformações
     */
    public alterarinformações() {
        initComponents();
         setExtendedState(MAXIMIZED_BOTH);
         this.verSenha.setVisible(false);
         this.verNovaSenha.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Sobrenome = new javax.swing.JTextField();
        boxGrau = new javax.swing.JComboBox<>();
        dataNasc = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        Nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        voltaLogin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        editarNome = new javax.swing.JButton();
        editarNasc = new javax.swing.JButton();
        editarNomeUsuario = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pwdNovaSenha = new javax.swing.JPasswordField();
        pwdsenhaAtual = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NomeUsuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pwdNovaSenha1 = new javax.swing.JPasswordField();
        editarSobrenome = new javax.swing.JButton();
        verSenha = new javax.swing.JButton();
        naoVerSenha = new javax.swing.JButton();
        verNovaSenha = new javax.swing.JButton();
        naoVerNovaSenha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(209, 235, 229));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\Data de nascimento.png")); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\Grau de escolaridade.png")); // NOI18N

        Sobrenome.setBackground(new java.awt.Color(220, 239, 235));
        Sobrenome.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        Sobrenome.setForeground(new java.awt.Color(51, 78, 73));
        Sobrenome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 3))); // NOI18N
        Sobrenome.setCaretColor(new java.awt.Color(0, 102, 102));
        Sobrenome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Sobrenome.setDisabledTextColor(new java.awt.Color(51, 78, 73));
        Sobrenome.setEnabled(false);
        Sobrenome.setFocusable(false);

        boxGrau.setBackground(new java.awt.Color(87, 144, 132));
        boxGrau.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        boxGrau.setForeground(new java.awt.Color(0, 102, 102));
        boxGrau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grau de escolaridade:", "1º Ano do Ensino Médio", "2º Ano do Ensino Médio", "3º Ano do Ensino Médio", "Ainda estou no Ensino Fundamental", "Já me formei" }));
        boxGrau.setAutoscrolls(true);
        boxGrau.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boxGrau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boxGrau.setFocusable(false);
        boxGrau.setLightWeightPopupEnabled(false);
        boxGrau.setName(""); // NOI18N
        boxGrau.setRequestFocusEnabled(false);
        boxGrau.setVerifyInputWhenFocusTarget(false);

        dataNasc.setBackground(new java.awt.Color(220, 239, 235));
        dataNasc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 3), new java.awt.Color(51, 78, 73))); // NOI18N
        dataNasc.setForeground(new java.awt.Color(51, 78, 73));
        try {
            dataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataNasc.setDisabledTextColor(new java.awt.Color(51, 78, 73));
        dataNasc.setEnabled(false);
        dataNasc.setFocusable(false);
        dataNasc.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\Nome de usuario.png")); // NOI18N

        Nome.setBackground(new java.awt.Color(220, 239, 235));
        Nome.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        Nome.setForeground(new java.awt.Color(51, 78, 73));
        Nome.setText(" ");
        Nome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 3))); // NOI18N
        Nome.setCaretColor(new java.awt.Color(0, 102, 102));
        Nome.setDisabledTextColor(new java.awt.Color(51, 78, 73));
        Nome.setEnabled(false);
        Nome.setFocusable(false);
        Nome.setSelectionColor(new java.awt.Color(0, 102, 102));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\Nome.png")); // NOI18N

        voltaLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\salvar (1).png")); // NOI18N
        voltaLogin.setContentAreaFilled(false);
        voltaLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltaLoginMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(190, 227, 219));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\ALTERE SUAS INFORMAÇÕES.png")); // NOI18N

        sair.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\sair.png")); // NOI18N
        sair.setContentAreaFilled(false);
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sair)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        editarNome.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\editor.png")); // NOI18N
        editarNome.setContentAreaFilled(false);
        editarNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarNomeMouseClicked(evt);
            }
        });

        editarNasc.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\editor.png")); // NOI18N
        editarNasc.setContentAreaFilled(false);
        editarNasc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarNascMouseClicked(evt);
            }
        });

        editarNomeUsuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\editor.png")); // NOI18N
        editarNomeUsuario.setContentAreaFilled(false);
        editarNomeUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarNomeUsuarioMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\Senha atual__.png")); // NOI18N

        pwdNovaSenha.setBackground(new java.awt.Color(220, 239, 235));
        pwdNovaSenha.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        pwdNovaSenha.setForeground(new java.awt.Color(51, 78, 73));
        pwdNovaSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 3))); // NOI18N
        pwdNovaSenha.setCaretColor(new java.awt.Color(0, 102, 102));

        pwdsenhaAtual.setBackground(new java.awt.Color(220, 239, 235));
        pwdsenhaAtual.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        pwdsenhaAtual.setForeground(new java.awt.Color(51, 78, 73));
        pwdsenhaAtual.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 3))); // NOI18N
        pwdsenhaAtual.setCaretColor(new java.awt.Color(0, 102, 102));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\Nova senha_.png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\Sobrenome_.png")); // NOI18N

        NomeUsuario.setBackground(new java.awt.Color(220, 239, 235));
        NomeUsuario.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        NomeUsuario.setForeground(new java.awt.Color(51, 78, 73));
        NomeUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 3))); // NOI18N
        NomeUsuario.setCaretColor(new java.awt.Color(0, 102, 102));
        NomeUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        NomeUsuario.setDisabledTextColor(new java.awt.Color(51, 78, 73));
        NomeUsuario.setEnabled(false);
        NomeUsuario.setFocusable(false);
        NomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeUsuarioActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\Nova dica de senha_.png")); // NOI18N

        pwdNovaSenha1.setBackground(new java.awt.Color(220, 239, 235));
        pwdNovaSenha1.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        pwdNovaSenha1.setForeground(new java.awt.Color(51, 78, 73));
        pwdNovaSenha1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 3))); // NOI18N
        pwdNovaSenha1.setCaretColor(new java.awt.Color(0, 102, 102));

        editarSobrenome.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\editor.png")); // NOI18N
        editarSobrenome.setContentAreaFilled(false);
        editarSobrenome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarSobrenomeMouseClicked(evt);
            }
        });

        verSenha.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\cadastro\\versenhaadm (1).png")); // NOI18N
        verSenha.setContentAreaFilled(false);
        verSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verSenhaMouseClicked(evt);
            }
        });

        naoVerSenha.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\cadastro\\naoversenhaadm (1).png")); // NOI18N
        naoVerSenha.setContentAreaFilled(false);
        naoVerSenha.setLabel("");
        naoVerSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                naoVerSenhaMouseClicked(evt);
            }
        });

        verNovaSenha.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\cadastro\\versenhaadm (1).png")); // NOI18N
        verNovaSenha.setContentAreaFilled(false);
        verNovaSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verNovaSenhaMouseClicked(evt);
            }
        });

        naoVerNovaSenha.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\cadastro\\naoversenhaadm (1).png")); // NOI18N
        naoVerNovaSenha.setContentAreaFilled(false);
        naoVerNovaSenha.setLabel("");
        naoVerNovaSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                naoVerNovaSenhaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editarNome))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editarNasc))
                            .addComponent(boxGrau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editarNomeUsuario))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel5)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(editarSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(jLabel8))
                                                    .addComponent(pwdNovaSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(pwdNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(verNovaSenha)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(naoVerNovaSenha))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel3))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(pwdsenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(verSenha)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(naoVerSenha))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(120, 120, 120)
                                        .addComponent(jLabel9)))
                                .addGap(913, 913, 913))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(597, 597, 597)
                        .addComponent(voltaLogin)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editarNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sobrenome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(Nome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editarSobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(naoVerSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pwdsenhaAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editarNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editarNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boxGrau, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pwdNovaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(verNovaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(naoVerNovaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pwdNovaSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(voltaLogin)
                .addGap(253, 253, 253))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sairActionPerformed

    private void editarNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarNomeMouseClicked
        Nome.setEditable(true);
        Nome.setEnabled(true);
        Nome.setFocusable(true);
    }//GEN-LAST:event_editarNomeMouseClicked

    private void editarNomeUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarNomeUsuarioMouseClicked
        NomeUsuario.setEditable(true);
        NomeUsuario.setEnabled(true);
        NomeUsuario.setFocusable(true);
    }//GEN-LAST:event_editarNomeUsuarioMouseClicked

    private void editarNascMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarNascMouseClicked
        dataNasc.setEditable(true);
        dataNasc.setEnabled(true);
        dataNasc.setFocusable(true);
    }//GEN-LAST:event_editarNascMouseClicked

    private void voltaLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltaLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_voltaLoginMouseClicked

    private void editarSobrenomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarSobrenomeMouseClicked
        Sobrenome.setEditable(true);
        Sobrenome.setEnabled(true);
        Sobrenome.setFocusable(true);
    }//GEN-LAST:event_editarSobrenomeMouseClicked

    private void NomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeUsuarioActionPerformed

    private void verSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verSenhaMouseClicked
        naoVerSenha.setVisible(true);
        verSenha.setVisible(false);
        pwdsenhaAtual.setEchoChar((char)0);
    }//GEN-LAST:event_verSenhaMouseClicked

    private void naoVerSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_naoVerSenhaMouseClicked
        verSenha.setVisible(true);
        naoVerSenha.setVisible(false);
        pwdsenhaAtual.setEchoChar('*');
    }//GEN-LAST:event_naoVerSenhaMouseClicked

    private void verNovaSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verNovaSenhaMouseClicked
         naoVerNovaSenha.setVisible(true);
        verNovaSenha.setVisible(false);
        pwdNovaSenha.setEchoChar((char)0);
    }//GEN-LAST:event_verNovaSenhaMouseClicked

    private void naoVerNovaSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_naoVerNovaSenhaMouseClicked
        verNovaSenha.setVisible(true);
        naoVerNovaSenha.setVisible(false);
        pwdNovaSenha.setEchoChar('*');
    }//GEN-LAST:event_naoVerNovaSenhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alterarinformações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alterarinformações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alterarinformações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alterarinformações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alterarinformações().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nome;
    private javax.swing.JTextField NomeUsuario;
    private javax.swing.JTextField Sobrenome;
    private javax.swing.JComboBox<String> boxGrau;
    private javax.swing.JFormattedTextField dataNasc;
    private javax.swing.JButton editarNasc;
    private javax.swing.JButton editarNome;
    private javax.swing.JButton editarNomeUsuario;
    private javax.swing.JButton editarSobrenome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton naoVerNovaSenha;
    private javax.swing.JButton naoVerSenha;
    private javax.swing.JPasswordField pwdNovaSenha;
    private javax.swing.JPasswordField pwdNovaSenha1;
    private javax.swing.JPasswordField pwdsenhaAtual;
    private javax.swing.JButton sair;
    private javax.swing.JButton verNovaSenha;
    private javax.swing.JButton verSenha;
    private javax.swing.JButton voltaLogin;
    // End of variables declaration//GEN-END:variables
}
