package Testednv;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.text.ParseException;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;

public class QuestoesView extends javax.swing.JFrame {

    /**
     * Creates new form EscolhaQuestoes
     */
    public QuestoesView() {
    	
        initComponents();
        QuestoesController con = new QuestoesController(this);
        
         setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Mat = new javax.swing.JButton();
        Port = new javax.swing.JButton();
        Lit = new javax.swing.JButton();
        Fis = new javax.swing.JButton();
        Qui = new javax.swing.JButton();
        Bio = new javax.swing.JButton();
        Geo = new javax.swing.JButton();
        His = new javax.swing.JButton();
        Red = new javax.swing.JButton();
        btnFinalizar = new JButton("Finalizar");
        add(btnFinalizar, BorderLayout.SOUTH);
        btnFinalizar.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 136, 136));
        jLabel2.setText("SELECIONE A MATÉRIA:");

        Mat.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\FERNANDA ESCOLA 2023\\POO\\TesteLogin\\Mat.png")); // NOI18N
        Mat.setContentAreaFilled(false);
        Mat.setName("Mat");

        Port.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\FERNANDA ESCOLA 2023\\POO\\TesteLogin\\Portugues.png")); // NOI18N
        Port.setContentAreaFilled(false);
        Port.setName("Port");

        Lit.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\FERNANDA ESCOLA 2023\\POO\\TesteLogin\\Literatura.png")); // NOI18N
        Lit.setContentAreaFilled(false);
        Lit.setName("Lit");

        Fis.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\FERNANDA ESCOLA 2023\\POO\\TesteLogin\\Fisica.png")); // NOI18N
        Fis.setContentAreaFilled(false);
        Fis.setName("Fis");

        Qui.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\FERNANDA ESCOLA 2023\\POO\\TesteLogin\\Quimica.png")); // NOI18N
        Qui.setContentAreaFilled(false);
        Qui.setName("Qui");

        Bio.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\FERNANDA ESCOLA 2023\\POO\\TesteLogin\\Biologia.png")); // NOI18N
        Bio.setContentAreaFilled(false);
        Bio.setName("Bio");

        Geo.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\FERNANDA ESCOLA 2023\\POO\\TesteLogin\\Geografia.png")); // NOI18N
        Geo.setContentAreaFilled(false);
        Geo.setName("Geo");

        His.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\FERNANDA ESCOLA 2023\\POO\\TesteLogin\\Historia.png")); // NOI18N
        His.setContentAreaFilled(false);
        His.setName("His");

        Red.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\FERNANDA ESCOLA 2023\\POO\\TesteLogin\\Redação.png")); // NOI18N
        Red.setActionCommand("");
        Red.setContentAreaFilled(false);
        Red.setName("Red");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lit)
                    .addComponent(Mat)
                    .addComponent(Port))
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Fis)
                    .addComponent(Bio)
                    .addComponent(Qui, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(His)
                    .addComponent(Geo)
                    .addComponent(Red))
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(121, 121, 121)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mat)
                    .addComponent(Fis)
                    .addComponent(Geo))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Qui)
                            .addComponent(Port))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lit)
                            .addComponent(Bio)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(His)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Red)))
                .addContainerGap(295, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    public void exibirQuestoes(List <QuestoesVO> questoesList) {
    	System.out.println("Funcionando");
    	
    	idD = JOptionPane.showInputDialog(null, "Digite seu id: ");
    	
    	id = Integer.parseInt(idD);
    	System.out.println(id);

    	jPanel1.removeAll();
    	jPanel1.setLayout(new GridLayout(0,1));
    	
        btnFinalizar.setVisible(true);

        
        buttonGroups = new HashMap<>();
        
        for (QuestoesVO questao : questoesList) {
            JLabel perguntaLabel = new JLabel(questao.getPergunta());
            jPanel1.add(perguntaLabel);

            JRadioButton radioButtonA = new JRadioButton(questao.getA());
            JRadioButton radioButtonB = new JRadioButton(questao.getB());
            JRadioButton radioButtonC = new JRadioButton(questao.getC());
            JRadioButton radioButtonD = new JRadioButton(questao.getD());
            JRadioButton radioButtonE = new JRadioButton(questao.getE());

            ButtonGroup buttonGroup = new ButtonGroup();
            buttonGroup.add(radioButtonA);
            buttonGroup.add(radioButtonB);
            buttonGroup.add(radioButtonC);
            buttonGroup.add(radioButtonD);
            buttonGroup.add(radioButtonE);

            buttonGroups.put(questao, buttonGroup);

            jPanel1.add(radioButtonA);
            jPanel1.add(radioButtonB);
            jPanel1.add(radioButtonC);
            jPanel1.add(radioButtonD);
            jPanel1.add(radioButtonE);
        }

        scrollpane = new JScrollPane(jPanel1);
        scrollpane.setPreferredSize(new Dimension(400, 400));
        scrollpane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);

        
        setLayout(new BorderLayout());
        add(scrollpane, BorderLayout.CENTER);
        add(btnFinalizar, BorderLayout.AFTER_LAST_LINE);

        jPanel1.revalidate();
        jPanel1.repaint();
        pontuacao = calcularPontuacao();
    }

    public int calcularPontuacao() {
        
        for (QuestoesVO questao : buttonGroups.keySet()) {
            ButtonGroup buttonGroup = buttonGroups.get(questao);
            String respostaSelecionada = getSelectedButtonText(buttonGroup);

            if (respostaSelecionada != null && respostaSelecionada.equals(questao.getResposta())) {
            	
                pontuacao++;
                
            }
        }
        return pontuacao;
        
    }
    
    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        Enumeration<AbstractButton> buttons = buttonGroup.getElements();
        while (buttons.hasMoreElements()) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getActionCommand();
            }
        }
        return null;
    }
    
    public void mostrarPontuacao(String materia, int id) {
    	
    	
    	System.out.println(id);
    	
    	dao.progresso(materia, id, pontuacao);
    	jPanel1.removeAll();
        JLabel pontuacaoLabel = new JLabel("Pontuação: " + pontuacao);
        jPanel1.add(pontuacaoLabel);
        jPanel1.revalidate();
        jPanel1.repaint();	
       
        
       
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new QuestoesView().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Bio;
    public javax.swing.JButton Fis;
    public javax.swing.JButton Geo;
    public javax.swing.JButton His;
    public javax.swing.JButton Lit;
    public javax.swing.JButton Mat;
    public javax.swing.JButton Port;
    public javax.swing.JButton Qui;
    public javax.swing.JButton Red;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    public JButton btnFinalizar;
    private JScrollPane scrollpane;
    Map<QuestoesVO, ButtonGroup> buttonGroups;
    public QuestoesDAO questoesDAO;
    public int pontuacao;
    public String idD;
    public int id;
    public QuestoesDAO dao = new QuestoesDAO();
    // End of variables declaration//GEN-END:variables
}