/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agenda;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Gisele Vieira
 */
public class agendaEstudante extends javax.swing.JFrame {

    /**
     * Creates new form agendaEstudante
     */
    public agendaEstudante() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanelCalendario = new javax.swing.JPanel();
        selecaoMes = new javax.swing.JComboBox<>();
        selecaoAno = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        lblS1 = new javax.swing.JLabel();
        lblS2 = new javax.swing.JLabel();
        lblS3 = new javax.swing.JLabel();
        lblS4 = new javax.swing.JLabel();
        lblS5 = new javax.swing.JLabel();
        lblS6 = new javax.swing.JLabel();
        lblS7 = new javax.swing.JLabel();
        t8 = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();
        t22 = new javax.swing.JLabel();
        t15 = new javax.swing.JLabel();
        t29 = new javax.swing.JLabel();
        t36 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        t9 = new javax.swing.JLabel();
        t16 = new javax.swing.JLabel();
        t23 = new javax.swing.JLabel();
        t30 = new javax.swing.JLabel();
        t37 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        t10 = new javax.swing.JLabel();
        t24 = new javax.swing.JLabel();
        t17 = new javax.swing.JLabel();
        t31 = new javax.swing.JLabel();
        t38 = new javax.swing.JLabel();
        t4 = new javax.swing.JLabel();
        t11 = new javax.swing.JLabel();
        t18 = new javax.swing.JLabel();
        t25 = new javax.swing.JLabel();
        t32 = new javax.swing.JLabel();
        t39 = new javax.swing.JLabel();
        t5 = new javax.swing.JLabel();
        t6 = new javax.swing.JLabel();
        t7 = new javax.swing.JLabel();
        t12 = new javax.swing.JLabel();
        t13 = new javax.swing.JLabel();
        t14 = new javax.swing.JLabel();
        t19 = new javax.swing.JLabel();
        t20 = new javax.swing.JLabel();
        t21 = new javax.swing.JLabel();
        t26 = new javax.swing.JLabel();
        t27 = new javax.swing.JLabel();
        t28 = new javax.swing.JLabel();
        t33 = new javax.swing.JLabel();
        t34 = new javax.swing.JLabel();
        t35 = new javax.swing.JLabel();
        t40 = new javax.swing.JLabel();
        t41 = new javax.swing.JLabel();
        t42 = new javax.swing.JLabel();
        tituloAgenda = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cardsAgenda = new javax.swing.JPanel();
        PanelBase1 = new javax.swing.JPanel();
        PanelInfo1 = new javax.swing.JPanel();
        lblAtivAgenda2 = new javax.swing.JLabel();
        lblAtivAgenda3 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        reacoes1 = new javax.swing.JPanel();
        reacao1 = new javax.swing.JButton();
        reacao2 = new javax.swing.JButton();
        reacao3 = new javax.swing.JButton();
        reacao5 = new javax.swing.JButton();
        reacao4 = new javax.swing.JButton();
        reacao6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(229, 255, 249));

        jPanel2.setBackground(new java.awt.Color(200, 222, 217));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\Winx Studies.png")); // NOI18N
        jLabel3.setText(" ");

        sair.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\SAIRR (2).png")); // NOI18N
        sair.setToolTipText("Sair");
        sair.setBorder(null);
        sair.setContentAreaFilled(false);
        sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1104, Short.MAX_VALUE)
                .addComponent(sair)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(215, 238, 234));

        jPanelCalendario.setBackground(new java.awt.Color(183, 213, 206));
        jPanelCalendario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 112, 101)));

        selecaoMes.setBackground(new java.awt.Color(229, 255, 249));
        selecaoMes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        selecaoMes.setForeground(new java.awt.Color(35, 61, 56));
        selecaoMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        selecaoMes.setToolTipText("Selecione o mês");
        selecaoMes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selecaoMes.setFocusable(false);
        selecaoMes.setLightWeightPopupEnabled(false);

        selecaoAno.setBackground(new java.awt.Color(229, 255, 249));
        selecaoAno.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        selecaoAno.setForeground(new java.awt.Color(35, 61, 56));
        selecaoAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ano", ";", ";", ";", ";", " " }));
        selecaoAno.setToolTipText("Selecione o ano");
        selecaoAno.setVerifyInputWhenFocusTarget(false);

        jPanel5.setBackground(new java.awt.Color(209, 235, 229));

        lblS1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblS1.setForeground(new java.awt.Color(11, 114, 94));
        lblS1.setText("Dom");

        lblS2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblS2.setForeground(new java.awt.Color(35, 61, 56));
        lblS2.setText("Seg");

        lblS3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblS3.setForeground(new java.awt.Color(35, 61, 56));
        lblS3.setText("Ter");

        lblS4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblS4.setForeground(new java.awt.Color(35, 61, 56));
        lblS4.setText("Qua");

        lblS5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblS5.setForeground(new java.awt.Color(35, 61, 56));
        lblS5.setText("Qui");

        lblS6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblS6.setForeground(new java.awt.Color(35, 61, 56));
        lblS6.setText("Sex");

        lblS7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblS7.setForeground(new java.awt.Color(35, 61, 56));
        lblS7.setText("Sab");

        t8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t8.setForeground(new java.awt.Color(11, 114, 94));
        t8.setText("0");

        t1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t1.setForeground(new java.awt.Color(11, 114, 94));
        t1.setText("0");
        t1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        t22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t22.setForeground(new java.awt.Color(11, 114, 94));
        t22.setText("0");

        t15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t15.setForeground(new java.awt.Color(11, 114, 94));
        t15.setText("0");

        t29.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t29.setForeground(new java.awt.Color(11, 114, 94));
        t29.setText("0");

        t36.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t36.setForeground(new java.awt.Color(11, 114, 94));
        t36.setText("0");

        t2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t2.setForeground(new java.awt.Color(35, 61, 56));
        t2.setText("0");

        t9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t9.setForeground(new java.awt.Color(35, 61, 56));
        t9.setText("0");

        t16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t16.setForeground(new java.awt.Color(35, 61, 56));
        t16.setText("0");

        t23.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t23.setForeground(new java.awt.Color(35, 61, 56));
        t23.setText("0");

        t30.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t30.setForeground(new java.awt.Color(35, 61, 56));
        t30.setText("0");

        t37.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t37.setForeground(new java.awt.Color(35, 61, 56));
        t37.setText("0");

        t3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t3.setForeground(new java.awt.Color(35, 61, 56));
        t3.setText("0");

        t10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t10.setForeground(new java.awt.Color(35, 61, 56));
        t10.setText("0");

        t24.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t24.setForeground(new java.awt.Color(35, 61, 56));
        t24.setText("0");

        t17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t17.setForeground(new java.awt.Color(35, 61, 56));
        t17.setText("0");

        t31.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t31.setForeground(new java.awt.Color(35, 61, 56));
        t31.setText("0");

        t38.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t38.setForeground(new java.awt.Color(35, 61, 56));
        t38.setText("0");

        t4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t4.setForeground(new java.awt.Color(35, 61, 56));
        t4.setText("0");

        t11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t11.setForeground(new java.awt.Color(35, 61, 56));
        t11.setText("0");

        t18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t18.setForeground(new java.awt.Color(35, 61, 56));
        t18.setText("0");

        t25.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t25.setForeground(new java.awt.Color(35, 61, 56));
        t25.setText("0");

        t32.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t32.setForeground(new java.awt.Color(35, 61, 56));
        t32.setText("0");

        t39.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t39.setForeground(new java.awt.Color(35, 61, 56));
        t39.setText("0");

        t5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t5.setForeground(new java.awt.Color(35, 61, 56));
        t5.setText("0");

        t6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t6.setForeground(new java.awt.Color(35, 61, 56));
        t6.setText("0");

        t7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t7.setForeground(new java.awt.Color(35, 61, 56));
        t7.setText("0");

        t12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t12.setForeground(new java.awt.Color(35, 61, 56));
        t12.setText("0");

        t13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t13.setForeground(new java.awt.Color(35, 61, 56));
        t13.setText("0");

        t14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t14.setForeground(new java.awt.Color(35, 61, 56));
        t14.setText("0");

        t19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t19.setForeground(new java.awt.Color(35, 61, 56));
        t19.setText("0");

        t20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t20.setForeground(new java.awt.Color(35, 61, 56));
        t20.setText("0");

        t21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t21.setForeground(new java.awt.Color(35, 61, 56));
        t21.setText("0");

        t26.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t26.setForeground(new java.awt.Color(35, 61, 56));
        t26.setText("0");

        t27.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t27.setForeground(new java.awt.Color(35, 61, 56));
        t27.setText("0");

        t28.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t28.setForeground(new java.awt.Color(35, 61, 56));
        t28.setText("0");

        t33.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t33.setForeground(new java.awt.Color(35, 61, 56));
        t33.setText("0");

        t34.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t34.setForeground(new java.awt.Color(35, 61, 56));
        t34.setText("0");

        t35.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t35.setForeground(new java.awt.Color(35, 61, 56));
        t35.setText("0");

        t40.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t40.setForeground(new java.awt.Color(35, 61, 56));
        t40.setText("0");

        t41.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t41.setForeground(new java.awt.Color(35, 61, 56));
        t41.setText("0");

        t42.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        t42.setForeground(new java.awt.Color(35, 61, 56));
        t42.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(t36, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t37, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t38, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t39, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t40, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t41, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t42, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(t29, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t30, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t31, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t32, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t33, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t34, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t35, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(t15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t20, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t21, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(t22, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t23, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t24, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t25, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t26, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t27, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t28, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(t14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblS1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblS2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(lblS3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(lblS4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(lblS5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(lblS6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(lblS7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblS1)
                    .addComponent(lblS2)
                    .addComponent(lblS3)
                    .addComponent(lblS4)
                    .addComponent(lblS5)
                    .addComponent(lblS6)
                    .addComponent(lblS7))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1)
                    .addComponent(t2)
                    .addComponent(t3)
                    .addComponent(t4)
                    .addComponent(t5)
                    .addComponent(t6)
                    .addComponent(t7))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t8)
                    .addComponent(t9)
                    .addComponent(t10)
                    .addComponent(t11)
                    .addComponent(t12)
                    .addComponent(t13)
                    .addComponent(t14))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t15)
                    .addComponent(t16)
                    .addComponent(t17)
                    .addComponent(t18)
                    .addComponent(t19)
                    .addComponent(t20)
                    .addComponent(t21))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t22)
                    .addComponent(t23)
                    .addComponent(t24)
                    .addComponent(t25)
                    .addComponent(t26)
                    .addComponent(t27)
                    .addComponent(t28))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t29)
                    .addComponent(t30)
                    .addComponent(t31)
                    .addComponent(t32)
                    .addComponent(t33)
                    .addComponent(t34)
                    .addComponent(t35))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t36)
                    .addComponent(t37)
                    .addComponent(t38)
                    .addComponent(t39)
                    .addComponent(t40)
                    .addComponent(t41)
                    .addComponent(t42))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCalendarioLayout = new javax.swing.GroupLayout(jPanelCalendario);
        jPanelCalendario.setLayout(jPanelCalendarioLayout);
        jPanelCalendarioLayout.setHorizontalGroup(
            jPanelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalendarioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(selecaoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selecaoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCalendarioLayout.setVerticalGroup(
            jPanelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalendarioLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selecaoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecaoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanelCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tituloAgenda.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\Agenda (1).png")); // NOI18N

        cardsAgenda.setBackground(new java.awt.Color(229, 255, 249));

        PanelBase1.setBackground(new java.awt.Color(229, 255, 249));

        PanelInfo1.setBackground(new java.awt.Color(183, 213, 206));

        lblAtivAgenda2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAtivAgenda2.setForeground(new java.awt.Color(35, 61, 56));
        lblAtivAgenda2.setText("Publicação dos gabaritos");

        lblAtivAgenda3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblAtivAgenda3.setForeground(new java.awt.Color(35, 61, 56));
        lblAtivAgenda3.setText("10/11/2023");

        btnAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\excluir (4).png")); // NOI18N
        btnAdd.setToolTipText("adicionar ou maudar reação");
        btnAdd.setBorderPainted(false);
        btnAdd.setContentAreaFilled(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelInfo1Layout = new javax.swing.GroupLayout(PanelInfo1);
        PanelInfo1.setLayout(PanelInfo1Layout);
        PanelInfo1Layout.setHorizontalGroup(
            PanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfo1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAtivAgenda2, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAtivAgenda3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(26, 26, 26))
        );
        PanelInfo1Layout.setVerticalGroup(
            PanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfo1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblAtivAgenda2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(lblAtivAgenda3)
                .addGap(22, 22, 22))
            .addGroup(PanelInfo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        reacoes1.setBackground(new java.awt.Color(229, 255, 249));

        reacao1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\excluir (4).png")); // NOI18N
        reacao1.setToolTipText("Excluir");
        reacao1.setBorderPainted(false);
        reacao1.setContentAreaFilled(false);
        reacao1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reacao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reacao1ActionPerformed(evt);
            }
        });

        reacao2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\excluir (4).png")); // NOI18N
        reacao2.setToolTipText("Excluir");
        reacao2.setBorderPainted(false);
        reacao2.setContentAreaFilled(false);
        reacao2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reacao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reacao2ActionPerformed(evt);
            }
        });

        reacao3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\excluir (4).png")); // NOI18N
        reacao3.setToolTipText("Excluir");
        reacao3.setBorderPainted(false);
        reacao3.setContentAreaFilled(false);
        reacao3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reacao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reacao3ActionPerformed(evt);
            }
        });

        reacao5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\excluir (4).png")); // NOI18N
        reacao5.setToolTipText("Excluir");
        reacao5.setBorderPainted(false);
        reacao5.setContentAreaFilled(false);
        reacao5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reacao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reacao5ActionPerformed(evt);
            }
        });

        reacao4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\excluir (4).png")); // NOI18N
        reacao4.setToolTipText("Excluir");
        reacao4.setBorderPainted(false);
        reacao4.setContentAreaFilled(false);
        reacao4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reacao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reacao4ActionPerformed(evt);
            }
        });

        reacao6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\excluir (4).png")); // NOI18N
        reacao6.setToolTipText("Excluir");
        reacao6.setBorderPainted(false);
        reacao6.setContentAreaFilled(false);
        reacao6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reacao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reacao6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reacoes1Layout = new javax.swing.GroupLayout(reacoes1);
        reacoes1.setLayout(reacoes1Layout);
        reacoes1Layout.setHorizontalGroup(
            reacoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reacoes1Layout.createSequentialGroup()
                .addGroup(reacoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reacoes1Layout.createSequentialGroup()
                        .addComponent(reacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reacao2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(reacoes1Layout.createSequentialGroup()
                        .addComponent(reacao3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reacao4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(reacoes1Layout.createSequentialGroup()
                        .addComponent(reacao5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reacao6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        reacoes1Layout.setVerticalGroup(
            reacoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reacoes1Layout.createSequentialGroup()
                .addGroup(reacoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(reacoes1Layout.createSequentialGroup()
                        .addGroup(reacoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reacao2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reacao3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(reacao4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(reacoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reacao5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reacao6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelBase1Layout = new javax.swing.GroupLayout(PanelBase1);
        PanelBase1.setLayout(PanelBase1Layout);
        PanelBase1Layout.setHorizontalGroup(
            PanelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBase1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(PanelInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reacoes1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        PanelBase1Layout.setVerticalGroup(
            PanelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBase1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reacoes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelBase1Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(PanelInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout cardsAgendaLayout = new javax.swing.GroupLayout(cardsAgenda);
        cardsAgenda.setLayout(cardsAgendaLayout);
        cardsAgendaLayout.setHorizontalGroup(
            cardsAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardsAgendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelBase1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        cardsAgendaLayout.setVerticalGroup(
            cardsAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardsAgendaLayout.createSequentialGroup()
                .addComponent(PanelBase1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 579, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(cardsAgenda);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(683, 683, 683)
                        .addComponent(tituloAgenda))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1486, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(451, 451, 451)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tituloAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sairActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        openMenuBar();
    }//GEN-LAST:event_btnAddActionPerformed

    private void reacao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reacao1ActionPerformed
        // TODO add your handling code here:
        closeMenuBar();
    }//GEN-LAST:event_reacao1ActionPerformed

    private void reacao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reacao2ActionPerformed
        // TODO add your handling code here:
        closeMenuBar();
    }//GEN-LAST:event_reacao2ActionPerformed

    private void reacao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reacao3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reacao3ActionPerformed

    private void reacao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reacao5ActionPerformed
        // TODO add your handling code here:
        closeMenuBar();
    }//GEN-LAST:event_reacao5ActionPerformed

    private void reacao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reacao4ActionPerformed
        // TODO add your handling code here:
        closeMenuBar();
    }//GEN-LAST:event_reacao4ActionPerformed

    private void reacao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reacao6ActionPerformed
        // TODO add your handling code here:
        closeMenuBar();
    }//GEN-LAST:event_reacao6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agendaEstudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agendaEstudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agendaEstudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agendaEstudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agendaEstudante().setVisible(true);
            }
        });
    }

        int w=425;
    int h=485;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBase1;
    private javax.swing.JPanel PanelInfo1;
    private javax.swing.JButton btnAdd;
    private javax.swing.JPanel cardsAgenda;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelCalendario;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAtivAgenda2;
    private javax.swing.JLabel lblAtivAgenda3;
    private javax.swing.JLabel lblS1;
    private javax.swing.JLabel lblS2;
    private javax.swing.JLabel lblS3;
    private javax.swing.JLabel lblS4;
    private javax.swing.JLabel lblS5;
    private javax.swing.JLabel lblS6;
    private javax.swing.JLabel lblS7;
    private javax.swing.JButton reacao1;
    private javax.swing.JButton reacao2;
    private javax.swing.JButton reacao3;
    private javax.swing.JButton reacao4;
    private javax.swing.JButton reacao5;
    private javax.swing.JButton reacao6;
    private javax.swing.JPanel reacoes1;
    private javax.swing.JButton sair;
    private javax.swing.JComboBox<String> selecaoAno;
    public javax.swing.JComboBox<String> selecaoMes;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t10;
    private javax.swing.JLabel t11;
    private javax.swing.JLabel t12;
    private javax.swing.JLabel t13;
    private javax.swing.JLabel t14;
    private javax.swing.JLabel t15;
    private javax.swing.JLabel t16;
    private javax.swing.JLabel t17;
    private javax.swing.JLabel t18;
    private javax.swing.JLabel t19;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t20;
    private javax.swing.JLabel t21;
    private javax.swing.JLabel t22;
    private javax.swing.JLabel t23;
    private javax.swing.JLabel t24;
    private javax.swing.JLabel t25;
    private javax.swing.JLabel t26;
    private javax.swing.JLabel t27;
    private javax.swing.JLabel t28;
    private javax.swing.JLabel t29;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t30;
    private javax.swing.JLabel t31;
    private javax.swing.JLabel t32;
    private javax.swing.JLabel t33;
    private javax.swing.JLabel t34;
    private javax.swing.JLabel t35;
    private javax.swing.JLabel t36;
    private javax.swing.JLabel t37;
    private javax.swing.JLabel t38;
    private javax.swing.JLabel t39;
    private javax.swing.JLabel t4;
    private javax.swing.JLabel t40;
    private javax.swing.JLabel t41;
    private javax.swing.JLabel t42;
    private javax.swing.JLabel t5;
    private javax.swing.JLabel t6;
    private javax.swing.JLabel t7;
    private javax.swing.JLabel t8;
    private javax.swing.JLabel t9;
    private javax.swing.JLabel tituloAgenda;
    // End of variables declaration//GEN-END:variables

 private void openMenuBar(){
        new Thread(new Runnable() {
            @Override
            public void run() {
                for(int i=0;i<w;i++){
                    reacoes1.setSize(w, h);
                    try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(agendaEstudante.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
}
       private void closeMenuBar(){
        new Thread(new Runnable() {
            @Override
            public void run() {
                for(int i=w;i>0;i--){
                    reacoes1.setSize(i, h);
                 
                }
            }
        }).start();
}
}
