/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Gisele Vieira
 */
public class editarQuestoes extends javax.swing.JFrame {

    /**
     * Creates new form editarQuestoes
     */
    public editarQuestoes() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoEnunciado = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        radioA1 = new javax.swing.JRadioButton();
        radioA2 = new javax.swing.JRadioButton();
        radioA3 = new javax.swing.JRadioButton();
        radioA4 = new javax.swing.JRadioButton();
        radioA5 = new javax.swing.JRadioButton();
        A1 = new javax.swing.JTextField();
        A2 = new javax.swing.JTextField();
        A3 = new javax.swing.JTextField();
        A4 = new javax.swing.JTextField();
        A5 = new javax.swing.JTextField();
        pSeletivo = new javax.swing.JComboBox<>();
        materia = new javax.swing.JComboBox<>();
        editarpSeletivo = new javax.swing.JButton();
        editarMateria = new javax.swing.JButton();
        editarEnunciado = new javax.swing.JButton();
        editarA1 = new javax.swing.JButton();
        editarA2 = new javax.swing.JButton();
        editarA3 = new javax.swing.JButton();
        editarA4 = new javax.swing.JButton();
        editarA5 = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        SAIR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(214, 255, 245));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\Editar Questões.png")); // NOI18N

        jPanel3.setBackground(new java.awt.Color(229, 255, 249));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\Enunciado_ (1).png")); // NOI18N

        campoEnunciado.setColumns(20);
        campoEnunciado.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        campoEnunciado.setForeground(new java.awt.Color(0, 102, 102));
        campoEnunciado.setRows(2);
        campoEnunciado.setCaretColor(new java.awt.Color(0, 102, 102));
        campoEnunciado.setEnabled(false);
        campoEnunciado.setFocusCycleRoot(true);
        campoEnunciado.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        campoEnunciado.setSelectionColor(new java.awt.Color(217, 252, 252));
        jScrollPane1.setViewportView(campoEnunciado);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\Alternativas_.png")); // NOI18N

        radioA1.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        radioA1.setForeground(new java.awt.Color(0, 73, 73));
        radioA1.setContentAreaFilled(false);
        radioA1.setEnabled(false);
        radioA1.setFocusable(false);
        radioA1.setMaximumSize(new java.awt.Dimension(150, 21));

        radioA2.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        radioA2.setForeground(new java.awt.Color(0, 73, 73));
        radioA2.setContentAreaFilled(false);
        radioA2.setEnabled(false);
        radioA2.setFocusable(false);
        radioA2.setMaximumSize(new java.awt.Dimension(150, 21));

        radioA3.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        radioA3.setForeground(new java.awt.Color(0, 73, 73));
        radioA3.setContentAreaFilled(false);
        radioA3.setEnabled(false);
        radioA3.setFocusable(false);
        radioA3.setMaximumSize(new java.awt.Dimension(150, 21));

        radioA4.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        radioA4.setForeground(new java.awt.Color(0, 73, 73));
        radioA4.setContentAreaFilled(false);
        radioA4.setEnabled(false);
        radioA4.setFocusable(false);
        radioA4.setMaximumSize(new java.awt.Dimension(150, 21));

        radioA5.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        radioA5.setForeground(new java.awt.Color(0, 73, 73));
        radioA5.setContentAreaFilled(false);
        radioA5.setEnabled(false);
        radioA5.setFocusable(false);
        radioA5.setMaximumSize(new java.awt.Dimension(150, 21));

        A1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        A1.setForeground(new java.awt.Color(1, 68, 68));
        A1.setCaretColor(new java.awt.Color(0, 102, 102));
        A1.setEnabled(false);
        A1.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        A1.setSelectionColor(new java.awt.Color(175, 211, 211));
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });

        A2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        A2.setForeground(new java.awt.Color(1, 68, 68));
        A2.setCaretColor(new java.awt.Color(0, 102, 102));
        A2.setEnabled(false);
        A2.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        A2.setSelectionColor(new java.awt.Color(175, 211, 211));
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });

        A3.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        A3.setForeground(new java.awt.Color(1, 68, 68));
        A3.setCaretColor(new java.awt.Color(0, 102, 102));
        A3.setEnabled(false);
        A3.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        A3.setSelectionColor(new java.awt.Color(175, 211, 211));
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });

        A4.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        A4.setForeground(new java.awt.Color(1, 68, 68));
        A4.setCaretColor(new java.awt.Color(0, 102, 102));
        A4.setEnabled(false);
        A4.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        A4.setSelectionColor(new java.awt.Color(175, 211, 211));
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });

        A5.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        A5.setForeground(new java.awt.Color(1, 68, 68));
        A5.setCaretColor(new java.awt.Color(0, 102, 102));
        A5.setEnabled(false);
        A5.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        A5.setSelectionColor(new java.awt.Color(175, 211, 211));
        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5ActionPerformed(evt);
            }
        });

        pSeletivo.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        pSeletivo.setForeground(new java.awt.Color(0, 80, 80));
        pSeletivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Processo Seletivo:", "Enem", "Macro", "SIS-1", "PSC-1", "SIS-2", "PSC-2", "SIS-3", "PSC-3" }));
        pSeletivo.setEnabled(false);
        pSeletivo.setFocusable(false);
        pSeletivo.setRequestFocusEnabled(false);

        materia.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        materia.setForeground(new java.awt.Color(0, 80, 80));
        materia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matéria:", "Matemátia", "Português", "Literatura", "Física", "Química", "Biologia" }));
        materia.setEnabled(false);
        materia.setFocusable(false);
        materia.setRequestFocusEnabled(false);

        editarpSeletivo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\editor.png")); // NOI18N
        editarpSeletivo.setContentAreaFilled(false);
        editarpSeletivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarpSeletivoMouseClicked(evt);
            }
        });
        editarpSeletivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarpSeletivoActionPerformed(evt);
            }
        });

        editarMateria.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\editor.png")); // NOI18N
        editarMateria.setContentAreaFilled(false);
        editarMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarMateriaMouseClicked(evt);
            }
        });
        editarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarMateriaActionPerformed(evt);
            }
        });

        editarEnunciado.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\editor.png")); // NOI18N
        editarEnunciado.setContentAreaFilled(false);
        editarEnunciado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarEnunciadoMouseClicked(evt);
            }
        });
        editarEnunciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEnunciadoActionPerformed(evt);
            }
        });

        editarA1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\editor.png")); // NOI18N
        editarA1.setContentAreaFilled(false);
        editarA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarA1MouseClicked(evt);
            }
        });
        editarA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarA1ActionPerformed(evt);
            }
        });

        editarA2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\editor.png")); // NOI18N
        editarA2.setContentAreaFilled(false);
        editarA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarA2MouseClicked(evt);
            }
        });
        editarA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarA2ActionPerformed(evt);
            }
        });

        editarA3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\editor.png")); // NOI18N
        editarA3.setContentAreaFilled(false);
        editarA3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarA3MouseClicked(evt);
            }
        });
        editarA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarA3ActionPerformed(evt);
            }
        });

        editarA4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\editor.png")); // NOI18N
        editarA4.setContentAreaFilled(false);
        editarA4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarA4MouseClicked(evt);
            }
        });
        editarA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarA4ActionPerformed(evt);
            }
        });

        editarA5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\editor.png")); // NOI18N
        editarA5.setContentAreaFilled(false);
        editarA5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarA5MouseClicked(evt);
            }
        });
        editarA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarA5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pSeletivo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editarpSeletivo)
                        .addGap(211, 211, 211)
                        .addComponent(materia, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editarMateria))
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(radioA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(A1, javax.swing.GroupLayout.DEFAULT_SIZE, 1213, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editarA1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(radioA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radioA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radioA4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radioA5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(A4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1213, Short.MAX_VALUE)
                                    .addComponent(A3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(A2)
                                    .addComponent(A5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editarA2)
                                    .addComponent(editarA3)
                                    .addComponent(editarA4)
                                    .addComponent(editarA5)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarEnunciado)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pSeletivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(materia))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editarMateria)
                            .addComponent(editarpSeletivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editarEnunciado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(radioA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editarA1)
                            .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(A2)
                    .addComponent(radioA2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editarA2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(radioA3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editarA3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(A3))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(radioA4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(A4))))
                            .addComponent(editarA4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(radioA5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(A5))))
                    .addComponent(editarA5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnFinalizar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\finalizar (1).png")); // NOI18N
        btnFinalizar.setContentAreaFilled(false);
        btnFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        SAIR.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gisele Vieira\\Downloads\\SAIRR.png")); // NOI18N
        SAIR.setContentAreaFilled(false);
        SAIR.setLabel("");
        SAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 703, Short.MAX_VALUE)
                .addComponent(btnFinalizar)
                .addGap(635, 635, 635))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(537, 537, 537)
                        .addComponent(SAIR)
                        .addGap(55, 55, 55))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SAIR, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnFinalizar)
                .addGap(163, 163, 163))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A1ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A2ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3ActionPerformed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A4ActionPerformed

    private void A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A5ActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void editarpSeletivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarpSeletivoMouseClicked
         pSeletivo.setEnabled(true);   
    }//GEN-LAST:event_editarpSeletivoMouseClicked

    private void editarpSeletivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarpSeletivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarpSeletivoActionPerformed

    private void editarMateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarMateriaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editarMateriaMouseClicked

    private void editarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarMateriaActionPerformed
        materia.setEnabled(true);
    }//GEN-LAST:event_editarMateriaActionPerformed

    private void editarEnunciadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarEnunciadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editarEnunciadoMouseClicked

    private void editarEnunciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEnunciadoActionPerformed
        campoEnunciado.setEnabled(true);
    }//GEN-LAST:event_editarEnunciadoActionPerformed

    private void editarA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarA1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editarA1MouseClicked

    private void editarA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarA1ActionPerformed
        radioA1.setEnabled(true);
        A1.setEnabled(true);
    }//GEN-LAST:event_editarA1ActionPerformed

    private void editarA2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarA2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editarA2MouseClicked

    private void editarA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarA2ActionPerformed
        radioA2.setEnabled(true);
        A2.setEnabled(true);
    }//GEN-LAST:event_editarA2ActionPerformed

    private void editarA3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarA3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editarA3MouseClicked

    private void editarA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarA3ActionPerformed
        radioA3.setEnabled(true);
        A3.setEnabled(true);
    }//GEN-LAST:event_editarA3ActionPerformed

    private void editarA4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarA4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editarA4MouseClicked

    private void editarA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarA4ActionPerformed
        radioA4.setEnabled(true);
        A4.setEnabled(true);
    }//GEN-LAST:event_editarA4ActionPerformed

    private void editarA5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarA5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editarA5MouseClicked

    private void editarA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarA5ActionPerformed
        radioA5.setEnabled(true);
        A5.setEnabled(true);
    }//GEN-LAST:event_editarA5ActionPerformed

    private void SAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SAIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editarQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editarQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editarQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editarQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editarQuestoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A1;
    private javax.swing.JTextField A2;
    private javax.swing.JTextField A3;
    private javax.swing.JTextField A4;
    private javax.swing.JTextField A5;
    private javax.swing.JButton SAIR;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JTextArea campoEnunciado;
    private javax.swing.JButton editarA1;
    private javax.swing.JButton editarA2;
    private javax.swing.JButton editarA3;
    private javax.swing.JButton editarA4;
    private javax.swing.JButton editarA5;
    private javax.swing.JButton editarEnunciado;
    private javax.swing.JButton editarMateria;
    private javax.swing.JButton editarpSeletivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> materia;
    private javax.swing.JComboBox<String> pSeletivo;
    private javax.swing.JRadioButton radioA1;
    private javax.swing.JRadioButton radioA2;
    private javax.swing.JRadioButton radioA3;
    private javax.swing.JRadioButton radioA4;
    private javax.swing.JRadioButton radioA5;
    // End of variables declaration//GEN-END:variables
}
